# Generated by Django 3.1.6 on 2021-04-02 14:59
import csv
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('golfer', '0003_add_golfer_city'),
    ]

    def add_city_data(apps, schema_editor):

        Golfer = apps.get_model('golfer', 'Golfer')

        try:
            filename = "golfersInput.csv"
            input_file = open(filename, 'r')
            file_lines = csv.reader(input_file)
            golfers_list = list(file_lines)

            for golfer in golfers_list:
                golfer[0].strip()
                golfer[1].strip()
                golfer[2].strip()

            input_file.close()

            for name, bdate, city in golfers_list:
                golfer = Golfer.objects.get(golfer_name=name)
                golfer.golfer_city = city
                golfer.save()

        except IOError:
            print("File Not Found Error.")

    def remove_city_data(apps, schema_editor):
        Golfer = apps.get_model('golfer', 'Golfer')

        Golfer.objects.update(golfer_city='unknown')


    operations = [
        migrations.RunPython(add_city_data, reverse_code=remove_city_data)
    ]
